### ISSUE TITLE
any foxy version ?

### ISSUE THREAD

**Issue by flydragon2018** [SCHUNK-SE-Co-KG/schunk_svh_ros_driver#4]
ubuntu 20+ foxy

**Comment by stefanscherzinger** [comment]
Hi,

This driver is available for ROS2 *Foxy*. You may install it with
```bash
sudo apt install ros-foxy-schunk-svh-driver ros-foxy-schunk-svh-library
```
or from source with [this branch](https://github.com/SCHUNK-GmbH-Co-KG/schunk_svh_ros_driver/tree/ros2-foxy#installation).
